// Generated by CoffeeScript 1.6.3
(function() {
  console.log($('button'));

  $('#bewareButton').click(function(event) {
    return $('h1').append("BOO!!!");
  });

  $('#trick').click(function(event) {
    var num;
    num = $('#counter').html();
    num = parseInt(num) + 1;
    return $('#counter').html(num);
  });

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
